### ISSUE TITLE
GET /api​/ui​/backend​/connections returns empty array after restart

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/IDS-ConfigurationManager#10]
After adding a Backend Connection (POST) and restarting the Configmanager `GET /api​/ui​/backend​/connections` returns an empty array.
After adding another Backend Connection (POST) `GET /api​/ui​/backend​/connections` returns both Backend Connections.

**Comment by goekhanKahriman** [comment]
Fixed bug in feature branch Routenhandling with commit-ID: 1348bea
