### ISSUE TITLE
NullPointerException on POST ​/api​/ui​/resource​/representation

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/IDS-ConfigurationManager#19]
1. Backend Connection added (`POST ​/api​/ui​/backend​/connection`)
2. Resource added (`POST /api​/ui​/resource`)
2. Route added (`POST/api​/ui​/approute`)
3. `POST/api​/ui​/resource​/representation` with resourceId & endpointId from above.
Configmanager error:
java.lang.NullPointerException\r\n\tat de.fraunhofer.isst.configmanager.configmanagement.service.UtilService.addEndpointToConnectorRepresentation(UtilService.java:109)

**Comment by goekhanKahriman** [comment]
Bug is fixed in Branch feature/Routenhandling with commit-ID: 0021f88
